### ISSUE TITLE
How to get Window tag?

### ISSUE THREAD

**Issue by frakc** [google/ExoPlayer#4693]
### Issue description
When i try to get window tag, i always get `null`. Generally happens after i change media source
### Reproduction steps

I feed concatenating mediaSource to player
```java
private MediaSource createMediaSource(ExoVideo exoVideo) {
    Utils utils = new Utils();
    MediaSource[] playlist =
        utils.getPlaylist(context, mediaDataSourceFactory, manifestDataSourceFactory);
    Log.e("mcheck", "createMediaSource: size " + playlist.length);
    if (playlist.length == 1) return playlist[0];
    ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource(playlist);
    return concatenatingMediaSource;
  }
```
Concatenatingmediasource consists of several HLS MS where i put tags. Each of them checked to be non null.
```java
 return new HlsMediaSource.Factory(mediaDataSourceFactory)
            .setAllowChunklessPreparation(true)
            .setTag(tag)
            .createMediaSource(uri);
```

I check for tag in onTracksChanged()
```java
 @Override @SuppressWarnings("ReferenceEquality")
    public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {
      Log.e("mcheck", "onTracksChanged: ");
      if (timeline != null) {
        Log.e("mcheck", "onTracksChanged: " + timeline.getWindowCount());
        if (timeline.getWindowCount() > 0) {
          Log.e("mcheck", "onTracksChanged: " + player.getCurrentTag());
          Log.e("mcheck", "onTracksChanged:||||||||||||||||||||||||||||||||||||||||||||||||||");
          for (int i = 0; i < timeline.getWindowCount(); i++) {
            Timeline.Window w = new Timeline.Window();
            timeline.getWindow(i, w,true);
            Log.e("mcheck", "onTracksAll: " + i + " " + w.tag);
          }
          Timeline.Window w = new Timeline.Window();
          timeline.getWindow(player.getCurrentWindowIndex(),w,true);
          EventBus.getDefault().post(new PlayingAdEvent(player.isPlayingAd()));
          playerCallback.onTrackEnded((String) w.tag,
              player.getCurrentWindowIndex());
        } else {

        }
      } else {
        Log.e("mcheck", "onTracksChanged: timeline null");
      }
    }
  }
```

when this method i called i getting following log, where all tags are null
```
    onTracksChanged: 
    onTracksChanged: 23
    onTracksChanged: null
    onTracksChanged:||||||||||||||||||||||||||||||||||||||||||||||||||
    onTracksAll: 0 null
    onTracksAll: 1 null
    onTracksAll: 2 null
    onTracksAll: 3 null
    onTracksAll: 4 null
    onTracksAll: 5 null
    onTracksAll: 6 null
    onTracksAll: 7 null
    onTracksAll: 8 null
    onTracksAll: 9 null
    onTracksAll: 10 null
    onTracksAll: 11 null
    onTracksAll: 12 null
    onTracksAll: 13 null
    onTracksAll: 14 null
    onTracksAll: 15 null
    onTracksAll: 16 null
    onTracksAll: 17 null
    onTracksAll: 18 null
    onTracksAll: 19 null
    onTracksAll: 20 null
    onTracksAll: 21 null
    onTracksAll: 22 null
```
### Version of ExoPlayer being used
version 2.8.2
